### ISSUE TITLE
About tab

### ISSUE THREAD

**Issue by EmilyRHowe** [stormwaterheatmap/website#10]
For the drop down menu, let's include the following in the following order: 

Background ( See slide guide called "All About Stormwater", which includes the Background text and a button to link to a suite of resources )
Documentation -> Technical Reference; API Reference; Github
User Stories

**Comment by cnilsen** [comment]
Fixed, like this: 
![image](https://user-images.githubusercontent.com/4753248/132711380-58dca33c-0365-4b51-9e04-3afaee2124c6.png)
