### ISSUE TITLE
Analyze a Watershed

### ISSUE THREAD

**Issue by EmilyRHowe** [stormwaterheatmap/website#14]
- [x] Once you analyze a single watershed, you can't go backwards to other tool elements without first clicking on StormwaterHeatmap.org.  Somehow, we need to identify that as the "home" screen to start over again; or figure out a way to go backwards. 
- [x] Age of Development:  Error generating chart message
- [x] Soils and Lithology: Error generating chart message
- [x] Scale on Stormwater Runoff Chart is too large to show data very well. 
- [x] Need to include explanation of what the Units are for the charts

**Comment by cnilsen** [comment]
chart function updated with ```make_chart(layer_object,ws,scale)```
