### ISSUE TITLE
Typo in Precipitation info

### ISSUE THREAD

**Issue by ericka-hegeman** [stormwaterheatmap/website#38]
There's a typo in the beginning of the first sentence in the Precipitation (in) and Precipitation (mm) information:
Methodology used to develop this dataset is documented in (Mauger et al., 2018). **it dataset** contains modeled hourly precipitation using the GFDL CM3 global climate model and the Representative Concentration Pathways (RCP) 8.5 scenario.

Similar to some other layers, why is the table of raster values all NA?

**Comment by cnilsen** [comment]
Fix will push out when raster data dictionary updaters are imported.
