### ISSUE TITLE
Site navigation

### ISSUE THREAD

**Issue by ericka-hegeman** [stormwaterheatmap/website#47]
This could only be an issue for me, but I find the navigation around the site a little confusing. When I click on the summary data, I would almost prefer a pop-up window of text, so I can stay on the map page. The side-bar of tabs that opens on the left side of the page in the summary text is confusing. I always want to go back the map (it's the centerpiece of the website) and don't want to get lost in those side-bars of summary text. If I'm in the summary text for a layer and I want to go back to the map, I have to find which tab in my browser it was open in. I would prefer a "back" button to return to the same map display. If I use the "view data layers" tab at the top, the map re-loads and I have to navigate back to the layer I was previously viewing.

**Comment by cnilsen** [comment]
limitation of docusarus/earthengine. More info opens in a new tab.
