### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by ericka-hegeman** [stormwaterheatmap/website#56]
I assumed the search bar at the top of the map was a general website search bar, but it's in fact a location/address search bar! I had no idea until I tried searching for information on the website about one of the data layers (Puget sound assessment units - what are these polygons and where did the data come from, but the way?). Maybe this search bar needs a little information button so users know what it's meant for?

**Comment by cnilsen** [comment]
This is a limitation of earth engine apps.
