### ISSUE TITLE
License and Terms link

### ISSUE THREAD

**Issue by EmilyRHowe** [stormwaterheatmap/website#6]
License and Terms link connects to Background page. 

Digital Review Committee recommends linking to the below page for License and Terms of use: 
https://www.conservationgateway.org/Pages/Terms-of-Use.aspx

**Comment by cnilsen** [comment]
@EmilyRHowe does this apply to software too, or just the website?

**Comment by cnilsen** [comment]
added link

**Comment by cnilsen** [comment]
Assuming for now that the terms apply to the webiste only.
