### ISSUE TITLE
"View Data Layers" Issues

### ISSUE THREAD

**Issue by EmilyRHowe** [stormwaterheatmap/website#8]
1. Information button does not lead anywhere yet. 
2. Hydrology Data Layers -> Runoff (add unit of measure to first one- which is millimeters)
3. Flow Duration Index- needs some kind of brief explanation/title that indicates what this index is indicating (ie. **Index of flow alteration compared to predeveloped and/or forested conditions**).  
4. Input Data Layers -> Legend for Precipitation is spelled incorrectly ("preciptation")
5. Input Data Layers-> Land Use   Captitalize "Open Space" in the legend to match other categories.  Also, this one loads really slowly
6.  Generally- not all the data layers have the same model domain. Some are clipped to our domain, others are broader.  Not sure it matters, but it might be good to indicate edges of our model domain? 
7. Add Pollution Data Layers to "Select Layer Type" drop down menu- (then add the pollution layers as we get them)

**Comment by cnilsen** [comment]
> Information button does not lead anywhere yet.
Removed - this will be added to the legend (cannot display hover text or popup in ee) 
> Hydrology Data Layers -> Runoff (add unit of measure to first one- which is millimeters)
fixed 
> Flow Duration Index- needs some kind of brief explanation/title that indicates what this index is indicating (ie. Index of flow alteration compared to predeveloped and/or forested conditions).
done 
> Input Data Layers -> Legend for Precipitation is spelled incorrectly ("preciptation")
done
> Input Data Layers-> Land Use Captitalize "Open Space" in the legend to match other categories. Also, this one loads really slowly
done
> Generally- not all the data layers have the same model domain. Some are clipped to our domain, others are broader. Not sure it matters, but it might be good to indicate edges of our model domain?
done - all clipped
> Add Pollution Data Layers to "Select Layer Type" drop down menu- (then add the pollution layers as we get them)
waiting...
